name: Build GTK4 Anylinux AppImage

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    container:
      image: ghcr.io/pkgforge-dev/archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          pacman -Syu --noconfirm base-devel wget gtk4 polkit rustup git tree
          rustup default stable
          cargo install cargo-strip

          git clone https://gitlab.com/kazamos/appgallery.git
          cd appgallery
          cargo build --release && cargo strip
          ./install.sh
          ./anylinux_appimage
          rm -rf target
          tree .

      # - name: Upload Compiled AppImage Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: AppImage-${{ matrix.arch }}
      #     path: ./dist/*.AppImage
